// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: examples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (example_name, example_description)
VALUES ($1, $2)
RETURNING example_id, example_name, example_description, example_created_at, example_updated_at
`

type CreateExampleParams struct {
	ExampleName        string      `json:"example_name"`
	ExampleDescription pgtype.Text `json:"example_description"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (*Example, error) {
	row := q.db.QueryRow(ctx, createExample, arg.ExampleName, arg.ExampleDescription)
	var i Example
	err := row.Scan(
		&i.ExampleID,
		&i.ExampleName,
		&i.ExampleDescription,
		&i.ExampleCreatedAt,
		&i.ExampleUpdatedAt,
	)
	return &i, err
}

const deleteExample = `-- name: DeleteExample :exec
DELETE FROM examples
WHERE example_id = $1
`

func (q *Queries) DeleteExample(ctx context.Context, exampleID int32) error {
	_, err := q.db.Exec(ctx, deleteExample, exampleID)
	return err
}

const getExample = `-- name: GetExample :one
SELECT example_id, example_name, example_description, example_created_at, example_updated_at FROM examples
WHERE example_id = $1
`

func (q *Queries) GetExample(ctx context.Context, exampleID int32) (*Example, error) {
	row := q.db.QueryRow(ctx, getExample, exampleID)
	var i Example
	err := row.Scan(
		&i.ExampleID,
		&i.ExampleName,
		&i.ExampleDescription,
		&i.ExampleCreatedAt,
		&i.ExampleUpdatedAt,
	)
	return &i, err
}

const updateExample = `-- name: UpdateExample :one
UPDATE examples
SET example_name = $2, example_description = $3
WHERE example_id = $1 RETURNING example_id, example_name, example_description, example_created_at, example_updated_at
`

type UpdateExampleParams struct {
	ExampleID          int32       `json:"example_id"`
	ExampleName        string      `json:"example_name"`
	ExampleDescription pgtype.Text `json:"example_description"`
}

func (q *Queries) UpdateExample(ctx context.Context, arg UpdateExampleParams) (*Example, error) {
	row := q.db.QueryRow(ctx, updateExample, arg.ExampleID, arg.ExampleName, arg.ExampleDescription)
	var i Example
	err := row.Scan(
		&i.ExampleID,
		&i.ExampleName,
		&i.ExampleDescription,
		&i.ExampleCreatedAt,
		&i.ExampleUpdatedAt,
	)
	return &i, err
}
