// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Example struct {
	ExampleID          int32            `json:"example_id"`
	ExampleName        string           `json:"example_name"`
	ExampleDescription pgtype.Text      `json:"example_description"`
	ExampleCreatedAt   pgtype.Timestamp `json:"example_created_at"`
	ExampleUpdatedAt   pgtype.Timestamp `json:"example_updated_at"`
}
