// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateExample(ctx context.Context, arg CreateExampleParams) (*Example, error)
	DeleteExample(ctx context.Context, exampleID int32) error
	GetExample(ctx context.Context, exampleID int32) (*Example, error)
	UpdateExample(ctx context.Context, arg UpdateExampleParams) (*Example, error)
}

var _ Querier = (*Queries)(nil)
